services:
  - type: web
    name: yt-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python download_video_server.py
    plan: free
    autoDeploy: true
